# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

# Use Node.js LTS as the base image
FROM node:20-slim AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install all dependencies (including dev dependencies for the build)
RUN --mount=type=cache,target=/root/.npm npm ci --ignore-scripts

# Copy source code
COPY . .

# Build the package
RUN --mount=type=cache,target=/root/.npm npm run build

# Prune dev dependencies for a smaller final image
RUN npm prune --production

# Minimal image for runtime
FROM node:20-slim

WORKDIR /app

# Copy only necessary artifacts from the builder stage
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json .
COPY --from=builder /app/scripts/notion-openapi.json ./scripts/notion-openapi.json

# Set default environment variables
ENV OPENAPI_MCP_HEADERS="{}"

# The command that will be run when the container starts.
# This is also compatible with the HuggingFace deployment which expects `dist/index.js`.
ENTRYPOINT ["node", "dist/index.js"]